stages:
  - verify

before_script:
   - docker pull <%= polydevDockerImage %>

validate:
   stage: verify
   script:
     - docker run --user $(id -u):$(id -g) -v $(pwd):/data  <%= polydevDockerImage %>make validate
   tags:
    - terraform